# To initialize the bucket, run:
# curl -X PUT --aws-sigv4 "aws:amz:eu:s3" --user admin:password http://localhost:9000/thumbs

[[containers]]
name = "thumbs-rustfs"
image = "rustfs/rustfs:1.0.0"
network = "thumbs"
ports = [
  "9000:9000",
  "9001:9001",
]
env = [
  "RUSTFS_CONSOLE_ENABLE=true",
]
secrets = [
  "S3_ACCESS_KEY:RUSTFS_ACCESS_KEY",
  "S3_SECRET_KEY:RUSTFS_SECRET_KEY",
]
volumes = ["thumbs-rustfs:/data"]

[[containers]]
name = "thumbs-redis"
image = "redis:latest"
network = "thumbs"
ports = ["6379:6379"]
volumes = ["thumbs-redis:/data"]
cmd = ["redis-server", "--save", "60", "1"]
